// Smoke test: import all modules to catch missing exports / broken paths
import './js/data/talents.js';
import './js/data/events.js';
import './js/data/enemies.js';
import './js/data/items.js';
import './js/data/npcs.js';
import './js/core/util.js';
import './js/core/hooks.js';
import './js/core/state.js';
import './js/systems/meta.js';
import './js/systems/reincarnation.js';
import './js/systems/life.js';
import './js/systems/shop.js';
import './js/systems/town.js';
import './js/systems/adventure.js';
import './js/systems/combat.js';
import './js/ui/log.js';
import './js/ui/juice.js';
import './js/ui/render.js';
import './js/main.js';
console.log('All modules import OK');
